<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default_profile.jpeg', upload_to='profiles/'),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default_profile.jpeg', upload_to='profiles/'),
        ),
    ]
>>>>>>> 49c1d749563c4b264d06f2cf3418138d200a600b
