# Generated by Django 5.1.7 on 2025-04-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default_profile.jpg', upload_to='profiles/'),
        ),
    ]
