# Generated by Django 5.1.7 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_address_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_crypto',
            field=models.CharField(blank=True, help_text='Favorite cryptocurrency symbol (e.g., BTC, ETH)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_alert_sent',
            field=models.BooleanField(default=False, help_text='Whether the price alert has been sent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target price to buy the cryptocurrency', max_digits=20, null=True),
        ),
    ]
