<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
    ]
>>>>>>> 49c1d749563c4b264d06f2cf3418138d200a600b
